# Generated by Django 5.1.15 on 2026-09-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('video_path', models.CharField(default='media/videos/test.mp4', max_length=255, verbose_name='视频文件路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '摄像头',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='键')),
                ('value', models.CharField(max_length=255, verbose_name='值')),
                ('label', models.CharField(default='', max_length=128, verbose_name='说明')),
            ],
            options={
                'verbose_name': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='CrossingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='入口线', max_length=64, verbose_name='名称')),
                ('points', models.JSONField(verbose_name='线段坐标')),
                ('enter_direction', models.JSONField(default=[[0, 1]], verbose_name='进店方向向量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='monitoring.camera')),
            ],
            options={
                'verbose_name': '入口绊线',
            },
        ),
        migrations.CreateModel(
            name='ShelfROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=64, verbose_name='货架名称')),
                ('shelf_code', models.CharField(blank=True, default='', max_length=32, verbose_name='货架编号')),
                ('shape_type', models.CharField(choices=[('rect', '矩形'), ('polygon', '多边形')], default='polygon', max_length=16, verbose_name='形状')),
                ('points', models.JSONField(verbose_name='坐标点')),
                ('color', models.CharField(default='#409EFF', max_length=16, verbose_name='显示颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='monitoring.camera')),
            ],
            options={
                'verbose_name': '货架ROI',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('crowd', '区域拥挤'), ('loiter', '异常逗留'), ('fall', '摔倒/异常姿态')], max_length=16, verbose_name='类型')),
                ('level', models.CharField(default='warning', max_length=8, verbose_name='级别')),
                ('message', models.CharField(max_length=255, verbose_name='内容')),
                ('track_id', models.IntegerField(blank=True, null=True, verbose_name='跟踪ID')),
                ('status', models.CharField(choices=[('pending', '未处理'), ('handled', '已处理')], default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera')),
                ('roi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.shelfroi')),
            ],
            options={
                'verbose_name': '告警',
            },
        ),
        migrations.CreateModel(
            name='DwellRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(verbose_name='跟踪ID')),
                ('enter_time', models.DateTimeField(verbose_name='进入时间')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('duration', models.FloatField(default=0, verbose_name='停留时长(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='进行中')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera')),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwell_records', to='monitoring.shelfroi')),
            ],
            options={
                'verbose_name': '驻留记录',
                'indexes': [models.Index(fields=['roi', 'enter_time'], name='monitoring__roi_id_3cf05f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(db_index=True, verbose_name='跟踪ID')),
                ('x', models.FloatField(verbose_name='归一化X')),
                ('y', models.FloatField(verbose_name='归一化Y')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera')),
            ],
            options={
                'verbose_name': '轨迹点',
                'indexes': [models.Index(fields=['camera', 'ts'], name='monitoring__camera__1bb69a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('hour', models.IntegerField(verbose_name='小时')),
                ('enter_count', models.IntegerField(default=0, verbose_name='进店人次')),
                ('exit_count', models.IntegerField(default=0, verbose_name='离店人次')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.camera')),
            ],
            options={
                'verbose_name': '客流统计',
                'unique_together': {('camera', 'date', 'hour')},
            },
        ),
    ]
